apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cactus-client-notifications-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  tls:
  - hosts:
    - ${CACTUS_CLIENT_NOTIFICATIONS_FQDN}
    secretName: user-interface-ingress-tls
  rules:
  - host: ${CACTUS_CLIENT_NOTIFICATIONS_FQDN}
    http:
      paths:
      - path: ${CACTUS_CLIENT_NOTIFICATIONS_MOUNT_POINT}
        pathType: Prefix
        backend:
          service:
            name: cactus-client-notifications-service
            port:
              number: 80